# Use Node.js LTS version
FROM node:20-alpine AS builder

# Create directory for the application
WORKDIR /app

# Copy over the monorepo
COPY package.json .
RUN npm add -g pnpm@8.7.4
RUN npm add -g turbo@1.10.12
COPY . .


# Install build dependencies
RUN apk add --update python3 make g++\
    && rm -rf /var/cache/apk/*

# Install Packages and build
RUN pnpm install
RUN turbo run build --filter={./apps/web}...

# Production Stage
FROM node:18-alpine AS production

# Install nginx
RUN apk add --update nginx

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy over the built react app
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

# Replace the default nginx.conf
COPY apps/web/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
