version: "3.8"

name: local-dev
services:
    mysql:
        container_name: prisma-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=banjo-rss
            - MYSQL_USER=prisma
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    redis:
        image: "redis:7.0"
        container_name: redis_container
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql-data:
    redis_data:
