version: "3.8"

name: local-dev
services:
    postgres:
        image: postgres:15.3
        environment:
            POSTGRES_USER: banjo
            POSTGRES_PASSWORD: banjo
            POSTGRES_DB: banjo-rss
        ports:
            - "5432:5432"
        volumes:
            - banjo-data:/var/lib/postgresql/data
    redis:
        image: "redis:7.0"
        container_name: redis_container
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    banjo-data:
